heartbeat.monitors:
- {id: green-0000, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0001, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0002, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0003, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0004, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0005, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0006, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0007, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0008, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0009, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0010, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0011, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0012, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0013, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0014, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0015, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0016, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0017, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0018, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0019, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0020, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0021, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0022, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0023, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0024, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0025, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0026, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0027, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0028, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0029, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0030, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0031, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0032, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0033, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0034, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0035, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0036, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0037, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0038, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0039, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0040, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0041, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0042, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0043, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0044, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0045, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0046, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0047, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0048, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0049, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0050, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0051, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0052, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0053, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0054, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0055, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0056, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0057, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0058, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0059, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0060, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0061, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0062, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0063, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0064, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0065, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0066, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0067, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0068, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0069, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0070, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0071, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0072, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0073, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0074, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0075, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0076, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0077, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0078, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0079, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0080, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0081, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0082, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0083, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0084, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0085, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0086, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0087, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0088, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0089, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0090, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0091, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0092, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0093, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0094, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0095, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0096, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0097, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0098, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
- {id: green-0099, schedule: '@every 10s', type: http, urls: 'http://localhost:5678'}
output.elasticsearch:
  hosts: ['localhost:9200']
processors:
- add_observer_metadata:
    geo: {location: '37.926868, -78.024902', name: '${GEO_NAME}'}

