heartbeat.monitors:
- id: 0000-yellow
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0001-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0002-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0003-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0004-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0005-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0006-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0007-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0008-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0009-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0010-red
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0011-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0012-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0013-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0014-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0015-yellow
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0016-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0017-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0018-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0019-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0020-red
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0021-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0022-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0023-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0024-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0025-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0026-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0027-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0028-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0029-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0030-yellow
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0031-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0032-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0033-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0034-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0035-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0036-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0037-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0038-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0039-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0040-red
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0041-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0042-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0043-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0044-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0045-yellow
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0046-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0047-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0048-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0049-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0050-red
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0051-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0052-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0053-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0054-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0055-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0056-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0057-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0058-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0059-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0060-yellow
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0061-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0062-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0063-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0064-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0065-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0066-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0067-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0068-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0069-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0070-red
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0071-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0072-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0073-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0074-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0075-yellow
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0076-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0077-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0078-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0079-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0080-red
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0081-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0082-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0083-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0084-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0085-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0086-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0087-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0088-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0089-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0090-yellow
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0091-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0092-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0093-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0094-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0095-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0096-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0097-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0098-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
- id: 0099-green
  schedule: '@every 30s'
  timeout: 1s
  type: http
  urls: http://localhost:5678
output.elasticsearch:
  hosts:
  - localhost:9200
processors:
- add_observer_metadata:
    geo:
      location: 37.926868, -78.024902
      name: ${GEO_NAME}

