# How to run this:
# This needs env set, and if multiple are run concurrently separate data paths
# `env GEO_NAME="minneapolis" ./heartbeat -e -d /tmp/hb1`
# `env GEO_NAME="st-paul" ./heartbeat -e -d /tmp/hb2`


heartbeat.config.monitors:
  # Directory + glob pattern to search for configuration files
  path: ${path.config}/monitors.d/*.yml
  # If enabled, heartbeat will periodically check the config.monitors path for changes
  reload.enabled: false
  # How often to check for changes
  reload.period: 5s

# Configure monitors inline
heartbeat.monitors:
- type: http
  id: occasional-issues
  urls: ["http://localhost:5678/pattern?r=200x60,500x20"]
  schedule: '@every 1s'
- type: http
  id: always-green
  urls: ["http://localhost:5678/"]
  schedule: '@every 1s'
  mode: all
- type: http
  id: always-down
  urls: ["http://localhost:5678/pattern?r=500x4,404x4"]
  schedule: '@every 1s'
  mode: all
- type: http
  id: mixed-1
  urls: ["http://localhost:5678/pattern?r=200x500,404x4"]
  schedule: '@every 1s'
  mode: all
- type: http
  id: mixed-2
  urls: ["http://localhost:5678/pattern?r=200x500,404x4"]
  schedule: '@every 1s'
  mode: all
- type: http
  id: mixed-3
  urls: ["http://localhost:5678/pattern?r=200x500,404x4"]
  schedule: '@every 1s'
  mode: all
- type: http
  id: mixed-4
  urls: ["http://localhost:5678/pattern?r=200x500,404x4"]
  schedule: '@every 1s'
  mode: all

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  #_source.enabled: false

setup.kibana:

output.elasticsearch:
  hosts: ["localhost:9200"]

processors:
  - add_observer_metadata: 
      geo: 
        name: "${GEO_NAME}"
        location: "37.926868, -78.024902"
